version: '3'
services:
  app-node:
    working_dir: /app-docker
    container_name: contanier-app-compose
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app-compose:ro
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mohammed
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: yamini
      ME_CONFIG_MONGODB_URL: mongodb://root:mohammed@mongo:27017/

volumes:
  mongo-db: